Ajout du tracking posthog sur le site
incubateur-ademe/territoires-en-transitions pull request #3212
Opened 2024-05-09 14:46 UTC by mariheck

2024-05-13 08:32 UTC, farnoux reviewed
👍

2024-05-13 08:32 UTC, farnoux commented on packages/site/middleware.ts
> +      *.posthog.com
Obligatoire d'ajouter ça au CSP même avec PostHog en reverse proxy ?

2024-05-14 07:59 UTC, derfurth requested changes
Globalement rien n'a été oublié sur le setup et la CI, mais on pourrait se passer du PageTracker pour le site en mettant `capture_pageview` à `true` lors de l'initialisation de PostHog. En effet rendre les `properties` du tracker optionnelles ne permet plus de voir si on a oublié de les passer coté app, auth et panier.

2024-05-14 07:59 UTC, derfurth commented on packages/ui/src/components/tracking/TrackPageView.tsx
> +  ? {properties?: TrackingPlan[N]['properties']}
Aie du coup ça casse le TrackingPlan, on pourrait ne pas utiliser TrackPageView dans le site.

2024-05-14 07:59 UTC, derfurth commented on packages/site/middleware.ts
> +      *.posthog.com
Oui pour le dev, non pour la prod.

2024-05-14 07:59 UTC, derfurth commented on packages/site/app/TrackPage.tsx
> +    <TrackPageView
On pourrait ne pas utiliser TrackPageView et demander à PH de faire la capture de page en auto avec `capture_pageview` à `true`  https://github.com/incubateur-ademe/territoires-en-transitions/blob/d92cb3edc26138fd6cff5730ebc77cb6d9a5e58d/packages/ui/src/components/tracking/TrackingProvider.tsx#L49

2024-05-22 12:24 UTC, merged