Refonte FA : page sans onglets
incubateur-ademe/territoires-en-transitions pull request #3254
Opened 2024-07-17 07:53 UTC by mariheck

Ticket : https://www.notion.so/accelerateur-transition-ecologique-ademe/Refonte-FA-page-sans-onglets-1b6ff8ee3ca34c23b4d6d8b5cb86db74?pvs=4
(sans le déplacement des fiches)

2024-07-17 15:51 UTC, marc-rutkowski commented on app.territoiresentransitions.react/src/app/pages/collectivite/PlansActions/FicheAction/Carte/FicheActionCard.tsx
Tu peux supprimer les lignes 51 à 55 maintenant que le delete() est appelée depuis `ModaleSuppression`.

2024-07-17 15:55 UTC, marc-rutkowski commented on app.territoiresentransitions.react/src/app/pages/collectivite/PlansActions/FicheAction/data/types.ts
> +  TFicheResume,
import inutile

2024-07-17 16:16 UTC, marc-rutkowski commented on app.territoiresentransitions.react/src/app/pages/collectivite/PlansActions/FicheActionNew/FicheActionDescription/ModaleSuppression.tsx
> +  const handleDelete = () => {
Ça fonctionne mais eslint met un avertissement puisque `close` ne semble pas encore défini ici, car il est donné plus bas à la fonction `render` ligne 37.
Tu pourrais inline directement la définition de ce `handleDelete` ligne 63 dans le `onClick`

2024-07-17 16:21 UTC, marc-rutkowski commented on app.territoiresentransitions.react/src/app/pages/collectivite/PlansActions/FicheActionNew/utils.ts
> +  return localDate.toISOString().slice(0, 10);
ça devrait pas plutôt être `const localDate = date ? new Date(date) : new Date();` pour gérer le cas où la date n'est pas fournie (chaîne vide) et qu'on veux avoir la date courante (cf `ModalePlanning.tsx` ligne 57)

2024-07-17 16:29 UTC, marc-rutkowski commented on app.territoiresentransitions.react/src/app/pages/collectivite/PlansActions/PlansActionsRoutes.tsx
> +          `${collectiviteFicheNonClasseePath}/old`,
On garde ces anciens chemins tant que le dev n'est pas terminé j'imagine ?

2024-07-17 16:32 UTC, marc-rutkowski requested changes
Super boulot ! Je t'ai laissé quelques commentaires.

2024-07-18 08:21 UTC, mariheck commented on app.territoiresentransitions.react/src/app/pages/collectivite/PlansActions/PlansActionsRoutes.tsx
> +          `${collectiviteFicheNonClasseePath}/old`,
Oui voilà, ça me permet de comparer les comportements des deux versions. Je supprimerai ces chemins en fin de cycle, en même temps que les fichiers qui ne sont plus utilisés.

2024-07-18 08:39 UTC, mariheck commented on app.territoiresentransitions.react/src/app/pages/collectivite/PlansActions/FicheActionNew/utils.ts
> +  return localDate.toISOString().slice(0, 10);
Bien vu. J'ai appliqué le même principe sur les deux autres fonctions getDate. J'ai aussi mis à jour `ModalePlanning` pour éviter d'avoir une valeur par défaut si le champ est vide.

2024-07-18 09:30 UTC, marc-rutkowski approved these changes

2024-07-18 14:12 UTC, merged