Ajout de crisp au site public
incubateur-ademe/territoires-en-transitions pull request #3331
Opened 2024-10-02 15:05 UTC by mariheck

2024-10-02 16:18 UTC, marc-rutkowski commented on packages/site/middleware.ts
> +    font-src 'self' client.crisp.chat;
```suggestion
    image.crisp.chat;
```

2024-10-02 16:29 UTC, marc-rutkowski requested changes
Quelques petits changements à faire mais sinon ça fonctionne.

2024-10-03 12:53 UTC, marc-rutkowski approved these changes

2024-10-03 19:39 UTC, farnoux approved these changes

2024-10-03 19:44 UTC, merged